# Sample parameters file for chlorophytes-annotation pipeline

# Input files (modify paths according to your data)
genome_fasta: "data/genome.fasta"
illumina_reads: "data/illumina/*_R{1,2}.fastq.gz"
nanopore_reads: "data/nanopore/reads.fastq.gz"
rna_reads: "data/rnaseq/*_R{1,2}.fastq.gz"
protein_db: "data/databases/stramenopiles_proteins.fasta"
rfam_db: "data/databases/Rfam.cm"
tpseudnana_cds: "data/references/tpseudnana_cds.fasta"
reference_genomes: "data/phylogenomics/reference_genomes.fasta"

# Output directory
outdir: "results"

# Resource limits
max_memory: "128.GB"
max_cpus: 16
max_time: "240.h"

# Tool-specific parameters
# FreeBayes (ploidy evaluation)
min_mapping_quality: 30
min_base_quality: 30
min_coverage: 4

# VCFtools (variant filtering)
min_depth: 10
min_quality: 10

# Infernal (RNA families)
evalue_threshold: 0.01

# EDTA (transposable elements)
edta_species: "others"

# Asgart (segmental duplications)
gap_size: 3000
min_sequence_length: 5000
min_identity_rate: 0.9

# BEDTools (overlap analysis)
min_overlap: 0.1

# STAR (transcriptome mapping)
star_sjdboverhang: 99
max_intron_length: 100000

# Trinity (transcriptome assembly)
trinity_max_memory: "50G"
trinity_cpu: 16

# CD-HIT-EST (clustering)
cdhit_identity: 0.95
cdhit_global: 1

# TransDecoder (ORF prediction)
min_protein_length: 20

# DIAMOND BLAST (homology search)
diamond_evalue: 1e-5
diamond_max_target_seqs: 1

# Braker2 (gene annotation)
braker_species: "generic"

# MAKER2 (gene annotation)
maker_cpus: 8

# BUSCO (annotation quality)
busco_lineage_eukaryota: "eukaryota_odb10"
busco_lineage_stramenopiles: "stramenopiles_odb10"
busco_mode: "genome"

# PANNZER2 (functional annotation)
pannzer_min_query_coverage: 0.4
pannzer_min_subject_coverage: 0.4
pannzer_min_alignment_length: 50

# KAAS (KEGG annotation)
kaas_organisms: "cre,bmi,pti,fcy,tps,ath,olu,mpu"

# Minimap2 (nanopore mapping)
minimap_preset: "map-ont"

# Modkit (methylation analysis)
modkit_percentile: 10
modkit_min_coverage: 1

# RAxML-NG (phylogenomics)
raxmlng_model: "LG+G4"
raxmlng_bootstrap: 100